// JavaScript Document
$(document).ready(function(){
	$("#button0").click(function(){
        $(".table1").show();
		$(".table2").show();
		$(".table3").show();
		$(".table4").show();
    });
    $("#button1").click(function(){
        $(".table1").show();
		$(".table2").hide();
		$(".table3").hide();
		$(".table4").hide();
    });
	 $("#button2").click(function(){
        $(".table1").hide();
		$(".table2").show();
		$(".table3").hide();
		$(".table4").hide();
    });
	 $("#button3").click(function(){
        $(".table1").hide();
		$(".table2").hide();
		$(".table3").show();
		$(".table4").hide();
    });
	 $("#button4").click(function(){
        $(".table1").hide();
		$(".table2").hide();
		$(".table3").hide();
		$(".table4").show();
    });
});
